services:

  frontend:
    build: ./frontend
    container_name: flower-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: flower-backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: flower_shop
      DB_USER: floweradmin
      DB_PASSWORD: flower123
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.4
    container_name: flower-db
    environment:
      MYSQL_DATABASE: flower_shop
      MYSQL_USER: admin
      MYSQL_PASSWORD: flower123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data:
